/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KinhDoanh;

import DataBase.DBAccess;
import LoginKH.DangNhap;
import QuanLi.QLSanPham;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import static LoginKH.DangNhap_1.sodienthoai;

/**
 *
 * @author ASUS
 */
public class ChiTietSanPham extends javax.swing.JFrame {
    Connection con;
    public PreparedStatement pet,pet2;
    public static ResultSet rs = null ,rs2 = null;

    /**
     * Creates new form ChiTietSanPham
     */
    
    public ChiTietSanPham(String IDSP){
        initComponents();
        LoadData(IDSP,sodienthoai);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblTenSP = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txpChitiet = new javax.swing.JTextPane();
        txtIDSP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtGia = new javax.swing.JFormattedTextField();
        txtLoai = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        spinSoluong = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        btnThemSanPham = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        cbThach = new javax.swing.JCheckBox();
        cbBanhflan = new javax.swing.JCheckBox();
        cbPhomai = new javax.swing.JCheckBox();
        cbSuongsao = new javax.swing.JCheckBox();
        cbTranchau = new javax.swing.JCheckBox();
        cbKhucbach = new javax.swing.JCheckBox();
        lblThach = new javax.swing.JLabel();
        lblBanhFlan = new javax.swing.JLabel();
        lblPhomai = new javax.swing.JLabel();
        lblTranchau = new javax.swing.JLabel();
        lblKhucbach = new javax.swing.JLabel();
        lblSuongsao = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thêm sản phẩm");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/9.jpg"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 30, 205, -1));

        jPanel4.setBackground(new java.awt.Color(204, 255, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTenSP.setBackground(new java.awt.Color(255, 255, 255));
        lblTenSP.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lblTenSP.setForeground(new java.awt.Color(255, 0, 0));
        jPanel4.add(lblTenSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 205, 28));

        jLabel4.setText("Mã sản phẩm");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 62, -1, -1));

        jScrollPane2.setViewportView(txpChitiet);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 99, 420, 90));

        txtIDSP.setBackground(new java.awt.Color(255, 255, 204));
        txtIDSP.setForeground(new java.awt.Color(51, 51, 255));
        jPanel4.add(txtIDSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 75, -1));

        jLabel3.setText("Giá : ");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        txtGia.setBackground(new java.awt.Color(255, 255, 204));
        txtGia.setForeground(new java.awt.Color(51, 51, 255));
        jPanel4.add(txtGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 120, -1));

        txtLoai.setBackground(new java.awt.Color(255, 255, 204));
        txtLoai.setForeground(new java.awt.Color(51, 51, 255));
        jPanel4.add(txtLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 130, -1));

        jLabel2.setText("Loại");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        spinSoluong.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));
        jPanel4.add(spinSoluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 78, -1));

        jLabel6.setText("Số lượng");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 13, 471, 292));

        btnThoat.setBackground(new java.awt.Color(153, 255, 255));
        btnThoat.setForeground(new java.awt.Color(51, 0, 204));
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Redo/Redo_16x16.png"))); // NOI18N
        btnThoat.setText("Exit");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel3.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 327, -1, -1));

        btnThemSanPham.setBackground(new java.awt.Color(204, 0, 0));
        btnThemSanPham.setForeground(new java.awt.Color(51, 51, 51));
        btnThemSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add/Add_16x16.png"))); // NOI18N
        btnThemSanPham.setText("Thêm SP");
        btnThemSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemSanPhamMouseClicked(evt);
            }
        });
        btnThemSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSanPhamActionPerformed(evt);
            }
        });
        jPanel3.add(btnThemSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 327, -1, -1));

        panel.setBackground(new java.awt.Color(255, 255, 204));
        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thêm Topping", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(204, 102, 0))); // NOI18N
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbThach.setBackground(new java.awt.Color(255, 255, 204));
        cbThach.setText("Thạch");
        panel.add(cbThach, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        cbBanhflan.setBackground(new java.awt.Color(255, 255, 204));
        cbBanhflan.setText("Bánh flan");
        panel.add(cbBanhflan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        cbPhomai.setBackground(new java.awt.Color(255, 255, 204));
        cbPhomai.setText("Phô mai");
        panel.add(cbPhomai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        cbSuongsao.setBackground(new java.awt.Color(255, 255, 204));
        cbSuongsao.setText("Sương sáo");
        panel.add(cbSuongsao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        cbTranchau.setBackground(new java.awt.Color(255, 255, 204));
        cbTranchau.setText("Trân châu");
        panel.add(cbTranchau, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        cbKhucbach.setBackground(new java.awt.Color(255, 255, 204));
        cbKhucbach.setText("Khúc bạch");
        panel.add(cbKhucbach, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        lblThach.setText("2000");
        panel.add(lblThach, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        lblBanhFlan.setText("5000");
        panel.add(lblBanhFlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        lblPhomai.setText("5000");
        panel.add(lblPhomai, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        lblTranchau.setText("2000");
        panel.add(lblTranchau, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        lblKhucbach.setText("4000");
        panel.add(lblKhucbach, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        lblSuongsao.setText("3000");
        panel.add(lblSuongsao, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jPanel3.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 13, 197, 292));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/imageCTSP.jpg"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 927, 376));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 927, 376));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoadData(String IDSP,String sodienthoai)
    {
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;Database=AppTraSua;user=DoanJava;password=12345";
            Connection con = DriverManager.getConnection(url);
            String sql = "select IDSP,TenSP,TenLoai,ChiTiet,Gia from Sanpham,Loai where IDSP = ? and Sanpham.IDLoai = Loai.IDLoai";
            pet = con.prepareStatement(sql);
            pet.setString(1, IDSP);
            rs = pet.executeQuery();
            while(rs.next() )
            {
                txtIDSP.setText(rs.getString("IDSP"));
                lblTenSP.setText(rs.getNString("TenSP"));
                txtLoai.setText(rs.getString("TenLoai"));
                txpChitiet.setText(rs.getNString("ChiTiet"));
                txtGia.setText(rs.getString("Gia"));
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        txtIDSP.setEditable(false);
        txtLoai.setEditable(false);
        txpChitiet.setEditable(false);
        txtGia.setEditable(false);
    }
    private void btnThemSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSanPhamActionPerformed
        // TODO add your handling code here:
        DBAccess acc = new DBAccess();
        acc.connect();
        if(spinSoluong.getValue().hashCode() > 10 || spinSoluong.getValue().hashCode() <= 0)
        {
            JOptionPane.showMessageDialog(this, "Số lượng sản phẩm ngoài khả năng !!!");
            spinSoluong.setValue(1);
        }
        else
        {
            String IDSP = txtIDSP.getText();
            String Thach = null ;
            String BanhFlan = null;
            String Phomai = null;
            String SuongSao = null;
            String TranChau = null;
            String KhucBach = null;
            String Topping = "";
            int GThach = 0;
            int GBanhFlan = 0;
            int GPhomai = 0;
            int GSuongsao = 0;
            int GTranChau = 0;
            int GKhucBach = 0;
            if(cbThach.isSelected() == false && cbBanhflan.isSelected() == false && cbPhomai.isSelected() == false && cbSuongsao.isSelected() == false && cbTranchau.isSelected() == false && cbKhucbach.isSelected() == false)
            {
                Topping = "Không có" ;
            }
            else
            {
                if(cbThach.isSelected() == true)
                {
                    Thach = cbThach.getText();
                    GThach = Integer.parseInt(lblThach.getText());
                }
                if(cbBanhflan.isSelected() == true)
                {
                    BanhFlan = cbBanhflan.getText();
                    GBanhFlan = Integer.parseInt(lblBanhFlan.getText());
                }
                if(cbPhomai.isSelected() == true)
                {
                    Phomai = cbPhomai.getText();
                    GPhomai = Integer.parseInt(lblPhomai.getText());
                }
                if(cbSuongsao.isSelected() == true)
                {
                    SuongSao = cbSuongsao.getText();
                    GSuongsao = Integer.parseInt(lblSuongsao.getText());
                }
                if(cbTranchau.isSelected() == true)
                {
                    TranChau = cbTranchau.getText();
                    GTranChau = Integer.parseInt(lblTranchau.getText());
                }
                if(cbKhucbach.isSelected() == true)
                {
                    KhucBach = cbKhucbach.getText();
                    GKhucBach = Integer.parseInt(lblKhucbach.getText());
                }
                String tp1 = "";
                String tp2 = "";
                String tp3 = "";
                String tp4 = "";
                String tp5 = "";
                String tp6 = "";
                if(Thach != null)
                {
                    tp1 = Thach + ",";
                }
                if(BanhFlan != null)
                {
                    tp2 = BanhFlan + ",";
                }
                if(Phomai != null)
                {
                    tp3 = Phomai + ",";
                }
                if(SuongSao != null)
                {
                    tp4 = SuongSao + ",";
                }
                if(TranChau != null)
                {
                    tp5 = TranChau + ",";
                }
                if(KhucBach != null)
                {
                    tp6 = KhucBach + ".";
                }
                Topping = tp1 + tp2 + tp3 + tp4 + tp5 + tp6 ;
            }  
            int SoLuong = (int) spinSoluong.getValue();
            int Gia = Integer.parseInt(txtGia.getText());
            int TongTienSP = 0;
            String IDHD = null;
            String IDHDTC = null;
            TongTienSP = (SoLuong * (GThach + GBanhFlan + GPhomai + GSuongsao + GTranChau + GKhucBach)) + (SoLuong * Gia) ;
            int TongTienSP1 = TongTienSP - (TongTienSP * 5/100 );
            System.out.println(sodienthoai+"','"+IDSP+"','"+SoLuong+"','"+Topping+"','"+TongTienSP+"','"+TongTienSP1);
            if(sodienthoai == null)
            {
                acc.Update("insert into GioHang values('"+sodienthoai+"','"+IDSP+"','"+SoLuong+"',N'"+Topping+"','"+TongTienSP+"','"+IDHD+"')  ");
                    int kq = acc.Update("insert into GioHangTC values('"+IDSP+"','"+SoLuong+"',N'"+Topping+"','"+TongTienSP+"','"+IDHDTC+"')  ");
                if(kq!=0)
                {
                    JOptionPane.showMessageDialog(null,"Đã thêm sản phẩm vào giỏ hàng !!!");
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Thất bại ??");
                }
            }
            else
            {
                int kq = acc.Update("insert into GioHang values('"+sodienthoai+"','"+IDSP+"','"+SoLuong+"',N'"+Topping+"','"+TongTienSP+"','"+IDHD+"')  ");
                if(kq!=0)
                {
                    JOptionPane.showMessageDialog(null,"Đã thêm sản phẩm vào giỏ hàng !!!");
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Thất bại ??");
                }
            }          
        }
    }//GEN-LAST:event_btnThemSanPhamActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnThemSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemSanPhamMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemSanPhamMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      /*  java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChiTietSanPham().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemSanPham;
    private javax.swing.JButton btnThoat;
    private javax.swing.JCheckBox cbBanhflan;
    private javax.swing.JCheckBox cbKhucbach;
    private javax.swing.JCheckBox cbPhomai;
    private javax.swing.JCheckBox cbSuongsao;
    private javax.swing.JCheckBox cbThach;
    private javax.swing.JCheckBox cbTranchau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBanhFlan;
    private javax.swing.JLabel lblKhucbach;
    private javax.swing.JLabel lblPhomai;
    private javax.swing.JLabel lblSuongsao;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JLabel lblThach;
    private javax.swing.JLabel lblTranchau;
    private javax.swing.JPanel panel;
    private javax.swing.JSpinner spinSoluong;
    private javax.swing.JTextPane txpChitiet;
    private javax.swing.JFormattedTextField txtGia;
    private javax.swing.JTextField txtIDSP;
    private javax.swing.JTextField txtLoai;
    // End of variables declaration//GEN-END:variables

}
