/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KinhDoanh;

import DataBase.DBAccess;
import KinhDoanh.Home;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class InHoaDon extends javax.swing.JFrame {

    Connection con;
    public PreparedStatement pet,pet1;
    public static ResultSet rs = null ,rs1 = null;
    /**
     * Creates new form QLOderTaicho
     */
    public InHoaDon() {
        initComponents();
        LoadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabGiohang = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtTongtien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtLoaithanhtoan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNgayDat = new javax.swing.JTextField();
        btnInhoadon = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hóa đơn");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabGiohang.setBackground(new java.awt.Color(255, 255, 204));
        tabGiohang.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        tabGiohang.setForeground(new java.awt.Color(255, 102, 102));
        tabGiohang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên SP", "Đơn Giá", "Số lượng", "Topping", "Tổng giá SP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabGiohang.setGridColor(new java.awt.Color(51, 51, 255));
        tabGiohang.setSelectionBackground(new java.awt.Color(153, 153, 255));
        tabGiohang.setSelectionForeground(new java.awt.Color(255, 0, 0));
        tabGiohang.getTableHeader().setReorderingAllowed(false);
        tabGiohang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabGiohangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabGiohang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 910, 210));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Tổng tiền");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, -1, -1));

        txtTongtien.setToolTipText("");
        txtTongtien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongtienActionPerformed(evt);
            }
        });
        getContentPane().add(txtTongtien, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 500, 130, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Loại thanh toán");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Ngày đặt");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, 20));
        getContentPane().add(txtLoaithanhtoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 150, 30));

        jLabel4.setText("VND");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 500, -1, -1));

        txtNgayDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayDatActionPerformed(evt);
            }
        });
        getContentPane().add(txtNgayDat, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 150, 30));

        btnInhoadon.setBackground(new java.awt.Color(255, 0, 0));
        btnInhoadon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnInhoadon.setForeground(new java.awt.Color(255, 255, 255));
        btnInhoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Favorites/Favorites_16x16.png"))); // NOI18N
        btnInhoadon.setText("In hóa đơn");
        btnInhoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInhoadonActionPerformed(evt);
            }
        });
        getContentPane().add(btnInhoadon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 127, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 38)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 204));
        jLabel5.setText("HÓA ĐƠN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));

        btnReset.setBackground(new java.awt.Color(255, 255, 255));
        btnReset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(0, 0, 255));
        btnReset.setText("Reload");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 80, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("TOCTOC");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("752 Lạc Long Quân f9 Tân Bình TPHCM");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("Hân hạnh chào quý khách !!!");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 200, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 140, 150));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/imageINHD.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void LoadData()
    {
        DBAccess acc = new DBAccess();
        try
        {
            rs = acc.Query("select TenSP,SoLuong,Topping,TongTienSP,Gia,IDGH,NgayDat,TongTien,TenLoaiTT \n" +
                         "  from GioHang,Sanpham,ThongKeOderTaiCho,LoaiTT \n" +
                         "  where LoaiTT.IDLTT = ThongKeOderTaiCho.IDLTT and Sanpham.IDSP = GioHang.IDSP and sodienthoai = 'null' and IDHDTC = (select MAX(IDHDTC) from ThongKeOderTaiCho) ");
            String [] arr = {"Tên SP","Đơn giá","Số lượng","Topping","Tổng tiền SP"};
            DefaultTableModel model = new DefaultTableModel(arr,0);
            while(rs.next())
            {
                txtNgayDat.setText(rs.getString("NgayDat"));
                txtLoaithanhtoan.setText(rs.getString("TenLoaiTT"));
                txtTongtien.setText(rs.getString("TongTien"));
                Vector vec = new Vector();
                vec.add(rs.getString("TenSP"));
                vec.add(rs.getString("Gia"));
                vec.add(rs.getInt("SoLuong")); 
                vec.add(rs.getString("Topping"));
                vec.add(rs.getInt("TongTienSP"));

                model.addRow(vec);
            }
            tabGiohang.setModel(model);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        txtNgayDat.setEditable(false);
        txtLoaithanhtoan.setEditable(false);
        txtTongtien.setEditable(false);
    }
    
    private void tabGiohangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabGiohangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabGiohangMouseClicked

    private void txtTongtienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongtienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongtienActionPerformed

    private void btnInhoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInhoadonActionPerformed
        // TODO add your handling code here:
        DBAccess acc = new DBAccess();
        acc.connect();
        acc.Update("delete from GioHang where sodienthoai = 'null' ");
        JOptionPane.showMessageDialog(this, "Xuất hóa đơn thành công");
        LoadData();
    }//GEN-LAST:event_btnInhoadonActionPerformed

    private void txtNgayDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayDatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayDatActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        LoadData();
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInhoadon;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabGiohang;
    private javax.swing.JTextField txtLoaithanhtoan;
    private javax.swing.JTextField txtNgayDat;
    private javax.swing.JTextField txtTongtien;
    // End of variables declaration//GEN-END:variables
}
