/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KinhDoanh;

/**
 *
 * @author Administrator
 */
public class LoaiGiaoHang extends javax.swing.JFrame {

    /**
     * Creates new form LoaiGiaoHang
     */
    public LoaiGiaoHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGiaohangOn = new javax.swing.JButton();
        btnTaicho = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnTrove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGiaohangOn.setBackground(new java.awt.Color(255, 255, 0));
        btnGiaohangOn.setForeground(new java.awt.Color(0, 0, 204));
        btnGiaohangOn.setText("Giao hàng Online");
        btnGiaohangOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaohangOnActionPerformed(evt);
            }
        });
        getContentPane().add(btnGiaohangOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 38, 189, 50));

        btnTaicho.setBackground(new java.awt.Color(255, 255, 0));
        btnTaicho.setForeground(new java.awt.Color(0, 0, 153));
        btnTaicho.setText("Tại chỗ");
        btnTaicho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaichoActionPerformed(evt);
            }
        });
        getContentPane().add(btnTaicho, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 122, 189, 42));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnTrove.setBackground(new java.awt.Color(204, 204, 255));
        btnTrove.setForeground(new java.awt.Color(255, 51, 51));
        btnTrove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Undo/Undo_16x16.png"))); // NOI18N
        btnTrove.setText("Trở về");
        btnTrove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTroveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(btnTrove)
                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addComponent(btnTrove)
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 288, 244));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGiaohangOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaohangOnActionPerformed
        // TODO add your handling code here:
        ThanhToanOL frm = new ThanhToanOL();
        this.setVisible(false);
        frm.setVisible(true);             
    }//GEN-LAST:event_btnGiaohangOnActionPerformed

    private void btnTaichoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaichoActionPerformed
        // TODO add your handling code here:
        ThanhToanTC frm = new ThanhToanTC();
        this.setVisible(false);
        frm.setVisible(true);  
    }//GEN-LAST:event_btnTaichoActionPerformed

    private void btnTroveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTroveActionPerformed
        // TODO add your handling code here:
        GioHang frm = new GioHang();
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btnTroveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoaiGiaoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoaiGiaoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoaiGiaoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoaiGiaoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoaiGiaoHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGiaohangOn;
    private javax.swing.JButton btnTaicho;
    private javax.swing.JButton btnTrove;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
