/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KinhDoanh;

import DataBase.DBAccess;
import DataBase.MyConnect;
import LoginKH.DangNhap;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import static LoginKH.DangNhap_1.sodienthoai;

/**
 *
 * @author ASUS
 */
public class Product extends javax.swing.JFrame {
    Connection con;
    public PreparedStatement pet;
    public static ResultSet rs = null ;


    /**
     * Creates new form MuaHang
     */
    public Product() {
        initComponents();
        LoadImage();
        KichThuoc();
        if(sodienthoai == null)
        {
            btnTaikhoan.setEnabled(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnTaikhoan = new javax.swing.JButton();
        btnGiohang = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnProduct = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnAnh10 = new javax.swing.JButton(){
            ImageIcon icon = new ImageIcon("src/image/5.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        btnAnh1 = new javax.swing.JButton(){
            ImageIcon icon = new ImageIcon("src/image/5.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        btnAnh3 = new javax.swing.JButton(){
            ImageIcon icon = new ImageIcon("src/ViSinh/images/bg.png");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        btnAnh7 = new javax.swing.JButton(){
            ImageIcon icon = new ImageIcon("src/image/5.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        btnAnh9 = new javax.swing.JButton(){
            ImageIcon icon = new ImageIcon("src/image/5.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        btnAnh8 = new javax.swing.JButton(){
            ImageIcon icon = new ImageIcon("src/image/5.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        btnAnh5 = new javax.swing.JButton(){
            ImageIcon icon = new ImageIcon("src/image/5.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        btnAnh4 = new javax.swing.JButton();
        btnAnh11 = new javax.swing.JButton();
        btnAnh13 = new javax.swing.JButton();
        btnAnh15 = new javax.swing.JButton(){
            ImageIcon icon = new ImageIcon("src/image/5.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        btnAnh16 = new javax.swing.JButton(){
            ImageIcon icon = new ImageIcon("src/image/5.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        btnAnh17 = new javax.swing.JButton(){
            ImageIcon icon = new ImageIcon("src/image/5.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        btnAnh18 = new javax.swing.JButton(){
            ImageIcon icon = new ImageIcon("src/image/5.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        btnAnh12 = new javax.swing.JButton();
        btnAnh14 = new javax.swing.JButton(){
            ImageIcon icon = new ImageIcon("src/image/5.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        btnAnh2 = new javax.swing.JButton(){
            ImageIcon icon = new ImageIcon("src/image/5.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        btnAnh6 = new javax.swing.JButton(){
            ImageIcon icon = new ImageIcon("src/image/5.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnThemTHQ = new javax.swing.JButton();
        btnThemTS = new javax.swing.JButton();
        btnThemTSX = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Product");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        btnTaikhoan.setBackground(new java.awt.Color(255, 255, 255));
        btnTaikhoan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnTaikhoan.setForeground(new java.awt.Color(0, 0, 204));
        btnTaikhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User/User_16x16.png"))); // NOI18N
        btnTaikhoan.setText("Account");
        btnTaikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaikhoanActionPerformed(evt);
            }
        });

        btnGiohang.setBackground(new java.awt.Color(255, 255, 255));
        btnGiohang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnGiohang.setForeground(new java.awt.Color(0, 0, 204));
        btnGiohang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/giohang.jpg"))); // NOI18N
        btnGiohang.setText("Cart");
        btnGiohang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiohangActionPerformed(evt);
            }
        });

        btnHome.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 51, 153));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Globe/Globe_16x16.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnProduct.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnProduct.setForeground(new java.awt.Color(0, 51, 153));
        btnProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Favorites/Favorites_16x16.png"))); // NOI18N
        btnProduct.setText("Product");
        btnProduct.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Vivaldi", 3, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnTaikhoan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGiohang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTaikhoan)
                    .addComponent(btnGiohang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 530));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(700, 991));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Trà hoa quả");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 670, -1, -1));

        btnAnh10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnh10ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAnh10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 130, 110));

        btnAnh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnh1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAnh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 65, 130, 110));

        btnAnh3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnh3ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAnh3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 125, 110));

        btnAnh7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnh7ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAnh7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 130, 110));

        btnAnh9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnh9ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAnh9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 130, 110));

        btnAnh8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnh8ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAnh8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 130, 110));

        btnAnh5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnh5ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAnh5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 130, 110));

        btnAnh4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnh4ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAnh4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 130, 110));

        btnAnh11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnh11ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAnh11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 130, 110));

        btnAnh13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnh13ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAnh13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 740, 130, 110));

        btnAnh15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnh15ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAnh15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 740, 130, 110));

        btnAnh16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnh16ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAnh16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 740, 130, 110));

        btnAnh17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnh17ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAnh17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 130, 110));

        btnAnh18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnh18ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAnh18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 130, 110));

        btnAnh12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnh12ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAnh12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, 130, 110));

        btnAnh14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnh14ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAnh14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 880, 130, 110));

        btnAnh2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnh2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAnh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 880, 125, 111));

        btnAnh6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnh6ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAnh6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 130, 110));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Trà sữa");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 13, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("Trà sữa xanh");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        btnThemTHQ.setBackground(new java.awt.Color(255, 255, 255));
        btnThemTHQ.setForeground(new java.awt.Color(153, 0, 153));
        btnThemTHQ.setText("Xem thêm");
        btnThemTHQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTHQActionPerformed(evt);
            }
        });
        jPanel3.add(btnThemTHQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 670, -1, -1));

        btnThemTS.setBackground(new java.awt.Color(255, 255, 255));
        btnThemTS.setForeground(new java.awt.Color(153, 0, 153));
        btnThemTS.setText("Xem thêm");
        btnThemTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTSActionPerformed(evt);
            }
        });
        jPanel3.add(btnThemTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        btnThemTSX.setBackground(new java.awt.Color(255, 255, 255));
        btnThemTSX.setForeground(new java.awt.Color(153, 0, 153));
        btnThemTSX.setText("Xem thêm");
        btnThemTSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTSXActionPerformed(evt);
            }
        });
        jPanel3.add(btnThemTSX, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        jScrollPane2.setViewportView(jPanel3);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 0, 750, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoadImage(){
        int MenuTS = 8;
        JButton[] btnList = {btnAnh1,btnAnh3,btnAnh4,btnAnh6,btnAnh7,btnAnh8,btnAnh10,btnAnh18};
        for(int i = 1; i <= MenuTS; i++)
        {
            ImageIcon icon = new ImageIcon("./src/Image/otherMenu/" + i + ".jpg");
            Image img = icon.getImage();
            Image imgScale = img.getScaledInstance(btnList[i-1].getWidth(), btnList[i-1].getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaleIcon = new ImageIcon(imgScale);
            btnList[i-1].setIcon(scaleIcon);
        }
        int MenuTSX = 5;
        JButton[] btnList1 = {btnAnh5,btnAnh9,btnAnh11,btnAnh12,btnAnh17};
        for(int i = 1; i <= MenuTSX; i++)
        {
            ImageIcon icon = new ImageIcon("./src/Image/milkTeaMenu/" + i + ".jpg");
            Image img = icon.getImage();
            Image imgScale = img.getScaledInstance(btnList1[i-1].getWidth(), btnList1[i-1].getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaleIcon = new ImageIcon(imgScale);
            btnList1[i-1].setIcon(scaleIcon);
        }
        int MenuTHQ = 5;
        JButton[] btnList2 = {btnAnh2,btnAnh13,btnAnh14,btnAnh15,btnAnh16};
        for(int i = 1; i <= MenuTHQ; i++)
        {
            ImageIcon icon = new ImageIcon("./src/Image/teaMenu/" + i + ".jpg");
            Image img = icon.getImage();
            Image imgScale = img.getScaledInstance(btnList2[i-1].getWidth(), btnList2[i-1].getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaleIcon = new ImageIcon(imgScale);
            btnList2[i-1].setIcon(scaleIcon);
        }
    }
    private void KichThuoc()
    {
        int Menu = 13;
        JButton[] btnList = {btnAnh1,btnAnh2,btnAnh3,btnAnh4,btnAnh5,btnAnh6,btnAnh7,btnAnh8,btnAnh9,btnAnh10,btnAnh11,btnAnh12,btnAnh13};
        for(int i = 1; i <= Menu; i++)
        {
            btnList[i-1].setSize(130, 130);
        }  
    }
    private void btnTaikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaikhoanActionPerformed
        // TODO add your handling code here:
        Account frm = new Account();
        frm.setVisible(true);
    }//GEN-LAST:event_btnTaikhoanActionPerformed

    private void btnGiohangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiohangActionPerformed
        // TODO add your handling code here:
        GioHang frm = new GioHang();
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btnGiohangActionPerformed

    private void btnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductActionPerformed
        // TODO add your handling code here:
        Product frm = new Product();
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btnProductActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        Home frm = new Home();
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnAnh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnh1ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBAccess acc = new DBAccess();
            ResultSet rs = acc.GetData4("SP01");
            while(rs.next())
            {
                btnAnh1.setText(rs.getString("IDSP"));
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        String IDSP = btnAnh1.getText().toString();
        ChiTietSanPham frm = new ChiTietSanPham(IDSP);
        frm.setVisible(true);
        btnAnh1.setText("");
    }//GEN-LAST:event_btnAnh1ActionPerformed

    private void btnAnh2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnh2ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBAccess acc = new DBAccess();
            ResultSet rs = acc.GetData4("SP02");
            while(rs.next())
            {
                btnAnh2.setText(rs.getString("IDSP"));
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        String IDSP = btnAnh2.getText().toString();
        ChiTietSanPham frm = new ChiTietSanPham(IDSP);
        frm.setVisible(true);
        btnAnh2.setText("");
    }//GEN-LAST:event_btnAnh2ActionPerformed

    private void btnAnh5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnh5ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBAccess acc = new DBAccess();
            ResultSet rs = acc.GetData4("SP05");
            while(rs.next())
            {
                btnAnh5.setText(rs.getString("IDSP"));
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        String IDSP = btnAnh5.getText().toString();
        ChiTietSanPham frm = new ChiTietSanPham(IDSP);
        frm.setVisible(true);
        btnAnh5.setText("");
    }//GEN-LAST:event_btnAnh5ActionPerformed

    private void btnAnh10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnh10ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBAccess acc = new DBAccess();
            ResultSet rs = acc.GetData4("SP10");
            while(rs.next())
            {
                btnAnh10.setText(rs.getString("IDSP"));
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        String IDSP = btnAnh10.getText().toString();
        ChiTietSanPham frm = new ChiTietSanPham(IDSP);
        frm.setVisible(true);
        btnAnh10.setText("");
    }//GEN-LAST:event_btnAnh10ActionPerformed

    private void btnAnh8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnh8ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBAccess acc = new DBAccess();
            ResultSet rs = acc.GetData4("SP08");
            while(rs.next())
            {
                btnAnh8.setText(rs.getString("IDSP"));
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        String IDSP = btnAnh8.getText().toString();
        ChiTietSanPham frm = new ChiTietSanPham(IDSP);
        frm.setVisible(true);
        btnAnh8.setText("");
    }//GEN-LAST:event_btnAnh8ActionPerformed

    private void btnAnh7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnh7ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBAccess acc = new DBAccess();
            ResultSet rs = acc.GetData4("SP07");
            while(rs.next())
            {
                btnAnh7.setText(rs.getString("IDSP"));
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        String IDSP = btnAnh7.getText().toString();
        ChiTietSanPham frm = new ChiTietSanPham(IDSP);
        frm.setVisible(true);
        btnAnh7.setText("");
    }//GEN-LAST:event_btnAnh7ActionPerformed

    private void btnAnh3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnh3ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBAccess acc = new DBAccess();
            ResultSet rs = acc.GetData4("SP03");
            while(rs.next())
            {
                btnAnh3.setText(rs.getString("IDSP"));
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        String IDSP = btnAnh3.getText().toString();
        ChiTietSanPham frm = new ChiTietSanPham(IDSP);
        frm.setVisible(true);
        btnAnh3.setText("");
    }//GEN-LAST:event_btnAnh3ActionPerformed

    private void btnAnh11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnh11ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBAccess acc = new DBAccess();
            ResultSet rs = acc.GetData4("SP11");
            while(rs.next())
            {
                btnAnh11.setText(rs.getString("IDSP"));
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        String IDSP = btnAnh11.getText().toString();
        ChiTietSanPham frm = new ChiTietSanPham(IDSP);
        frm.setVisible(true);
        btnAnh11.setText("");
    }//GEN-LAST:event_btnAnh11ActionPerformed

    private void btnAnh13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnh13ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBAccess acc = new DBAccess();
            ResultSet rs = acc.GetData4("SP13");
            while(rs.next())
            {
                btnAnh13.setText(rs.getString("IDSP"));
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        String IDSP = btnAnh13.getText().toString();
        ChiTietSanPham frm = new ChiTietSanPham(IDSP);
        frm.setVisible(true);
        btnAnh13.setText("");
    }//GEN-LAST:event_btnAnh13ActionPerformed

    private void btnAnh9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnh9ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBAccess acc = new DBAccess();
            ResultSet rs = acc.GetData4("SP09");
            while(rs.next())
            {
                btnAnh9.setText(rs.getString("IDSP"));
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        String IDSP = btnAnh9.getText().toString();
        ChiTietSanPham frm = new ChiTietSanPham(IDSP);
        frm.setVisible(true);
        btnAnh9.setText("");
    }//GEN-LAST:event_btnAnh9ActionPerformed

    private void btnAnh12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnh12ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBAccess acc = new DBAccess();
            ResultSet rs = acc.GetData4("SP12");
            while(rs.next())
            {
                btnAnh12.setText(rs.getString("IDSP"));
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        String IDSP = btnAnh12.getText().toString();
        ChiTietSanPham frm = new ChiTietSanPham(IDSP);
        frm.setVisible(true);
        btnAnh12.setText("");
    }//GEN-LAST:event_btnAnh12ActionPerformed

    private void btnAnh6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnh6ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBAccess acc = new DBAccess();
            ResultSet rs = acc.GetData4("SP06");
            while(rs.next())
            {
                btnAnh6.setText(rs.getString("IDSP"));
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        String IDSP = btnAnh6.getText().toString();
        ChiTietSanPham frm = new ChiTietSanPham(IDSP);
        frm.setVisible(true);
        btnAnh6.setText("");
    }//GEN-LAST:event_btnAnh6ActionPerformed

    private void btnAnh4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnh4ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBAccess acc = new DBAccess();
            ResultSet rs = acc.GetData4("SP04");
            while(rs.next())
            {
                btnAnh4.setText(rs.getString("IDSP"));
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        String IDSP = btnAnh4.getText().toString();
        ChiTietSanPham frm = new ChiTietSanPham(IDSP);
        frm.setVisible(true);
        btnAnh4.setText("");
    }//GEN-LAST:event_btnAnh4ActionPerformed

    private void btnAnh14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnh14ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBAccess acc = new DBAccess();
            ResultSet rs = acc.GetData4("SP14");
            while(rs.next())
            {
                btnAnh14.setText(rs.getString("IDSP"));
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        String IDSP = btnAnh14.getText().toString();
        ChiTietSanPham frm = new ChiTietSanPham(IDSP);
        frm.setVisible(true);
        btnAnh14.setText("");
    }//GEN-LAST:event_btnAnh14ActionPerformed

    private void btnAnh15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnh15ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBAccess acc = new DBAccess();
            ResultSet rs = acc.GetData4("SP15");
            while(rs.next())
            {
                btnAnh15.setText(rs.getString("IDSP"));
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        String IDSP = btnAnh15.getText().toString();
        ChiTietSanPham frm = new ChiTietSanPham(IDSP);
        frm.setVisible(true);
        btnAnh15.setText("");
    }//GEN-LAST:event_btnAnh15ActionPerformed

    private void btnAnh16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnh16ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBAccess acc = new DBAccess();
            ResultSet rs = acc.GetData4("SP16");
            while(rs.next())
            {
                btnAnh16.setText(rs.getString("IDSP"));
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        String IDSP = btnAnh16.getText().toString();
        ChiTietSanPham frm = new ChiTietSanPham(IDSP);
        frm.setVisible(true);
        btnAnh16.setText("");
    }//GEN-LAST:event_btnAnh16ActionPerformed

    private void btnAnh17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnh17ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBAccess acc = new DBAccess();
            ResultSet rs = acc.GetData4("SP17");
            while(rs.next())
            {
                btnAnh17.setText(rs.getString("IDSP"));
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        String IDSP = btnAnh17.getText().toString();
        ChiTietSanPham frm = new ChiTietSanPham(IDSP);
        frm.setVisible(true);
        btnAnh17.setText("");
    }//GEN-LAST:event_btnAnh17ActionPerformed

    private void btnAnh18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnh18ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBAccess acc = new DBAccess();
            ResultSet rs = acc.GetData4("SP18");
            while(rs.next())
            {
                btnAnh18.setText(rs.getString("IDSP"));
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        String IDSP = btnAnh18.getText().toString();
        ChiTietSanPham frm = new ChiTietSanPham(IDSP);
        frm.setVisible(true);
        btnAnh18.setText("");
    }//GEN-LAST:event_btnAnh18ActionPerformed

    private void btnThemTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTSActionPerformed
        // TODO add your handling code here:
        TraSua frm = new TraSua();
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btnThemTSActionPerformed

    private void btnThemTSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTSXActionPerformed
        // TODO add your handling code here:
        TraSuaXanh frm = new TraSuaXanh();
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btnThemTSXActionPerformed

    private void btnThemTHQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTHQActionPerformed
        // TODO add your handling code here:
        TraHoaQua frm = new TraHoaQua();
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btnThemTHQActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnh1;
    private javax.swing.JButton btnAnh10;
    private javax.swing.JButton btnAnh11;
    private javax.swing.JButton btnAnh12;
    private javax.swing.JButton btnAnh13;
    private javax.swing.JButton btnAnh14;
    private javax.swing.JButton btnAnh15;
    private javax.swing.JButton btnAnh16;
    private javax.swing.JButton btnAnh17;
    private javax.swing.JButton btnAnh18;
    private javax.swing.JButton btnAnh2;
    private javax.swing.JButton btnAnh3;
    private javax.swing.JButton btnAnh4;
    private javax.swing.JButton btnAnh5;
    private javax.swing.JButton btnAnh6;
    private javax.swing.JButton btnAnh7;
    private javax.swing.JButton btnAnh8;
    private javax.swing.JButton btnAnh9;
    private javax.swing.JButton btnGiohang;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnProduct;
    private javax.swing.JButton btnTaikhoan;
    private javax.swing.JButton btnThemTHQ;
    private javax.swing.JButton btnThemTS;
    private javax.swing.JButton btnThemTSX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
