/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KinhDoanh;

import DataBase.DBAccess;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static KinhDoanh.GioHang.TongTien;
import static LoginKH.DangNhap_1.sodienthoai;
/**
 *
 * @author ASUS
 */
public class ThanhToanTC extends javax.swing.JFrame {
    Connection con;
    public PreparedStatement pet;
    public static ResultSet rs = null ;
    public Statement stmt;

    /**
     * Creates new form ThanhToan
     */
    public ThanhToanTC() {
        initComponents();
        LoadData();
        LoadData2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbbLoaiThanhToan = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        spinNgaydat = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        btnThanhtoan = new javax.swing.JButton();
        btnGiohang = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtKhuyenmai = new javax.swing.JTextPane();
        jLabel13 = new javax.swing.JLabel();
        txtSoluong = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtMucKM = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTongtien = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnTrove = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbbLoaiThanhToan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thẻ ATM nội đia", "Tiền mặt", "Momo" }));
        getContentPane().add(cbbLoaiThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 131, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Loại thanh toán");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setText("Ngày đặt");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        spinNgaydat.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), new java.util.Date(), java.util.Calendar.MONTH));
        getContentPane().add(spinNgaydat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 140, 30));

        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Tổng tiền");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        btnThanhtoan.setBackground(new java.awt.Color(255, 0, 0));
        btnThanhtoan.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhtoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Favorites/Favorites_16x16.png"))); // NOI18N
        btnThanhtoan.setText("Thanh toán");
        btnThanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhtoanActionPerformed(evt);
            }
        });
        getContentPane().add(btnThanhtoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        btnGiohang.setBackground(new java.awt.Color(255, 255, 0));
        btnGiohang.setForeground(new java.awt.Color(102, 102, 255));
        btnGiohang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/giohang.jpg"))); // NOI18N
        btnGiohang.setText("Cart");
        btnGiohang.setPreferredSize(new java.awt.Dimension(85, 25));
        btnGiohang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiohangActionPerformed(evt);
            }
        });
        getContentPane().add(btnGiohang, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel12.setForeground(new java.awt.Color(0, 0, 204));
        jLabel12.setText("Dịp khuyến mãi");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jScrollPane2.setViewportView(txtKhuyenmai);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 180, 40));

        jLabel13.setForeground(new java.awt.Color(0, 0, 204));
        jLabel13.setText("Số lượng còn");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));
        getContentPane().add(txtSoluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 60, 25));

        jLabel14.setForeground(new java.awt.Color(0, 0, 204));
        jLabel14.setText("Khuyến mãi");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));
        getContentPane().add(txtMucKM, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 60, 25));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel15.setText("%");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 20, 20));
        getContentPane().add(txtTongtien, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 103, -1));

        jLabel1.setText("VND");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));

        btnTrove.setBackground(new java.awt.Color(255, 255, 204));
        btnTrove.setForeground(new java.awt.Color(0, 0, 153));
        btnTrove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Undo/Undo_16x16.png"))); // NOI18N
        btnTrove.setText("Trở về");
        btnTrove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTroveActionPerformed(evt);
            }
        });
        getContentPane().add(btnTrove, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/TC.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoadData()
    {
        DBAccess acc = new DBAccess();
        try
        {
            rs = acc.Query("select * from KhuyenMai where TinhTrangKM = N'Mở'");
            while(rs.next() )
            {
                txtKhuyenmai.setText(rs.getString("DipKhuyenMai"));
                txtSoluong.setText(rs.getString("SoLuong"));
                txtMucKM.setText(rs.getString("MucKM"));
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        spinNgaydat.setEnabled(false);
        txtKhuyenmai.setEditable(false);
        txtSoluong.setEditable(false);
        txtMucKM.setEditable(false);
        txtTongtien.setEditable(false);
    }
    public void LoadData2()
    {
        int MucKhuyenMai = Integer.parseInt(txtMucKM.getText());     
        double TongTienTT = TongTien - (TongTien * (MucKhuyenMai * 1/100));
        txtTongtien.setText(""+TongTienTT);
    }
    private void btnThanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhtoanActionPerformed
        // TODO add your handling code here:
        DBAccess acc = new DBAccess();
        acc.connect();
        String DipKM = txtKhuyenmai.getText();
        int MucKhuyenMai = Integer.parseInt(txtMucKM.getText());
        int SoLuong = Integer.parseInt(txtSoluong.getText());
        SoLuong = SoLuong - 1;
        String IDLTT = (String) cbbLoaiThanhToan.getSelectedItem();
        SimpleDateFormat formater = new SimpleDateFormat("hh:mm:ss,dd/MM/yyyy");
        String NgayDat = formater.format(spinNgaydat.getValue());
        double TongTienTC = Double.parseDouble(txtTongtien.getText()) ;
        int result = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn đặt hàng ???","Xác nhận",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(result  == JOptionPane.YES_OPTION)
        {
            try {
                acc.InsertOderTC(IDLTT, NgayDat,  MucKhuyenMai ,TongTienTC);
            } catch (SQLException ex) {
                Logger.getLogger(ThanhToanTC.class.getName()).log(Level.SEVERE, null, ex);
            }
            acc.Update("update KhuyenMai set  SoLuong = '"+SoLuong+"' where DipKhuyenMai = N'"+DipKM+"'");
            JOptionPane.showMessageDialog(this, "TocToc cảm ơn quý khách !"
            + "Hẹn gặp lại quý khách lần sau !");

            this.setVisible(false);
            Home frm = new Home();
            frm.setVisible(true);
            acc.Update("update GioHangTC set IDHDTC = (select IDHDTC from ThongKeOderTaiCho where IDHDTC = (select MAX(IDHDTC) from ThongKeOderTaiCho)) where IDHDTC = 'null' ");
        }          
    }//GEN-LAST:event_btnThanhtoanActionPerformed

    private void btnGiohangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiohangActionPerformed
        // TODO add your handling code here:
        GioHang frm = new GioHang();
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btnGiohangActionPerformed

    private void btnTroveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTroveActionPerformed
        // TODO add your handling code here:
        LoaiGiaoHang frm = new LoaiGiaoHang();
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btnTroveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThanhToanTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThanhToanTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThanhToanTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThanhToanTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThanhToanTC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGiohang;
    private javax.swing.JButton btnThanhtoan;
    private javax.swing.JButton btnTrove;
    private javax.swing.JComboBox<String> cbbLoaiThanhToan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner spinNgaydat;
    private javax.swing.JTextPane txtKhuyenmai;
    private javax.swing.JTextField txtMucKM;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtTongtien;
    // End of variables declaration//GEN-END:variables
}
