/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KinhDoanh;
import DataBase.DBAccess;
import DataBase.MyConnect;
import LoginKH.DangNhap;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static LoginKH.DangNhap_1.sodienthoai;
import javax.swing.JButton;
/**
 *
 * @author ASUS
 */
public class TraSua extends javax.swing.JFrame {

    /**
     * Creates new form TraSua
     */
    public TraSua() {
        initComponents();
        LoadImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        btnThoat = new javax.swing.JButton();
        btnAnh1 = new javax.swing.JButton(){
            ImageIcon icon = new ImageIcon("src/image/5.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jLabel3 = new javax.swing.JLabel();
        btnAnh3 = new javax.swing.JButton(){
            ImageIcon icon = new ImageIcon("src/ViSinh/images/bg.png");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        btnAnh10 = new javax.swing.JButton(){
            ImageIcon icon = new ImageIcon("src/image/5.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        btnAnh4 = new javax.swing.JButton();
        btnAnh7 = new javax.swing.JButton(){
            ImageIcon icon = new ImageIcon("src/image/5.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        btnAnh18 = new javax.swing.JButton(){
            ImageIcon icon = new ImageIcon("src/image/5.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        btnAnh6 = new javax.swing.JButton(){
            ImageIcon icon = new ImageIcon("src/image/5.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        btnAnh8 = new javax.swing.JButton(){
            ImageIcon icon = new ImageIcon("src/image/5.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(660, 500));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnThoat.setBackground(new java.awt.Color(255, 255, 255));
        btnThoat.setForeground(new java.awt.Color(204, 0, 204));
        btnThoat.setText("Exit");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel3.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        btnAnh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnh1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAnh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 65, 130, 110));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Trà sữa");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btnAnh3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnh3ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAnh3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 125, 110));

        btnAnh10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnh10ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAnh10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 130, 110));

        btnAnh4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnh4ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAnh4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 130, 110));

        btnAnh7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnh7ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAnh7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 130, 110));

        btnAnh18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnh18ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAnh18, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 130, 110));

        btnAnh6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnh6ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAnh6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 130, 110));

        btnAnh8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnh8ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAnh8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 130, 110));

        jScrollPane2.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoadImage(){
        int MenuTS = 8;
        JButton[] btnList = {btnAnh1,btnAnh3,btnAnh4,btnAnh6,btnAnh7,btnAnh8,btnAnh10,btnAnh18};
        for(int i = 1; i <= MenuTS; i++)
        {
            ImageIcon icon = new ImageIcon("./src/Image/otherMenu/" + i + ".jpg");
            Image img = icon.getImage();
            Image imgScale = img.getScaledInstance(btnList[i-1].getWidth(), btnList[i-1].getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaleIcon = new ImageIcon(imgScale);
            btnList[i-1].setIcon(scaleIcon);
        }
    }
    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        Product frm = new Product();
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnAnh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnh1ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBAccess acc = new DBAccess();
            ResultSet rs = acc.GetData4("SP01");
            while(rs.next())
            {
                btnAnh1.setText(rs.getString("IDSP"));
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        String IDSP = btnAnh1.getText().toString();
        ChiTietSanPham frm = new ChiTietSanPham(IDSP);
        frm.setVisible(true);
        btnAnh1.setText("");
    }//GEN-LAST:event_btnAnh1ActionPerformed

    private void btnAnh3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnh3ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBAccess acc = new DBAccess();
            ResultSet rs = acc.GetData4("SP03");
            while(rs.next())
            {
                btnAnh3.setText(rs.getString("IDSP"));
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        String IDSP = btnAnh3.getText().toString();
        ChiTietSanPham frm = new ChiTietSanPham(IDSP);
        frm.setVisible(true);
        btnAnh3.setText("");
    }//GEN-LAST:event_btnAnh3ActionPerformed

    private void btnAnh10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnh10ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBAccess acc = new DBAccess();
            ResultSet rs = acc.GetData4("SP10");
            while(rs.next())
            {
                btnAnh10.setText(rs.getString("IDSP"));
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        String IDSP = btnAnh10.getText().toString();
        ChiTietSanPham frm = new ChiTietSanPham(IDSP);
        frm.setVisible(true);
        btnAnh10.setText("");
    }//GEN-LAST:event_btnAnh10ActionPerformed

    private void btnAnh4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnh4ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBAccess acc = new DBAccess();
            ResultSet rs = acc.GetData4("SP04");
            while(rs.next())
            {
                btnAnh4.setText(rs.getString("IDSP"));
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        String IDSP = btnAnh4.getText().toString();
        ChiTietSanPham frm = new ChiTietSanPham(IDSP);
        frm.setVisible(true);
        btnAnh4.setText("");
    }//GEN-LAST:event_btnAnh4ActionPerformed

    private void btnAnh7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnh7ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBAccess acc = new DBAccess();
            ResultSet rs = acc.GetData4("SP07");
            while(rs.next())
            {
                btnAnh7.setText(rs.getString("IDSP"));
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        String IDSP = btnAnh7.getText().toString();
        ChiTietSanPham frm = new ChiTietSanPham(IDSP);
        frm.setVisible(true);
        btnAnh7.setText("");
    }//GEN-LAST:event_btnAnh7ActionPerformed

    private void btnAnh18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnh18ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBAccess acc = new DBAccess();
            ResultSet rs = acc.GetData4("SP18");
            while(rs.next())
            {
                btnAnh18.setText(rs.getString("IDSP"));
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        String IDSP = btnAnh18.getText().toString();
        ChiTietSanPham frm = new ChiTietSanPham(IDSP);
        frm.setVisible(true);
        btnAnh18.setText("");
    }//GEN-LAST:event_btnAnh18ActionPerformed

    private void btnAnh6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnh6ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBAccess acc = new DBAccess();
            ResultSet rs = acc.GetData4("SP06");
            while(rs.next())
            {
                btnAnh6.setText(rs.getString("IDSP"));
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        String IDSP = btnAnh6.getText().toString();
        ChiTietSanPham frm = new ChiTietSanPham(IDSP);
        frm.setVisible(true);
        btnAnh6.setText("");
    }//GEN-LAST:event_btnAnh6ActionPerformed

    private void btnAnh8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnh8ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBAccess acc = new DBAccess();
            ResultSet rs = acc.GetData4("SP08");
            while(rs.next())
            {
                btnAnh8.setText(rs.getString("IDSP"));
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        String IDSP = btnAnh8.getText().toString();
        ChiTietSanPham frm = new ChiTietSanPham(IDSP);
        frm.setVisible(true);
        btnAnh8.setText("");
    }//GEN-LAST:event_btnAnh8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TraSua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TraSua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TraSua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TraSua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TraSua().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnh1;
    private javax.swing.JButton btnAnh10;
    private javax.swing.JButton btnAnh18;
    private javax.swing.JButton btnAnh3;
    private javax.swing.JButton btnAnh4;
    private javax.swing.JButton btnAnh6;
    private javax.swing.JButton btnAnh7;
    private javax.swing.JButton btnAnh8;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
