/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLi;
import DataBase.DBAccess;

import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.ButtonGroup;
/**
 *
 * @author ASUS
 */
public class QLNhanvien extends javax.swing.JFrame {
    Connection con;
    public PreparedStatement pet;
    public static ResultSet rs = null ;
    public Statement stmt;
    
    /**
     * Creates new form Nhanvien
     */
    public QLNhanvien() {
        initComponents();
        ButtonGroup group = new ButtonGroup();
        group.add(rdbNu);
        group.add(rdbNam);
        LoadData();
        rdbNu.setSelected(true);
    }
    public void LoadData () 
    {
        DBAccess acc = new DBAccess();
        acc.connect();
        try { 
            rs = acc.GetData1();
            tabNhanvien.removeAll();
            String [] arr = {"IDNV","Username","Giới tính","SDT","Chức vụ","Địa chỉ"};
            DefaultTableModel model = new DefaultTableModel(arr,0);
            while(rs.next())
            {
                Vector vec = new Vector();
                vec.add(rs.getString("IDNV"));
                vec.add(rs.getString("Username"));
                vec.add(rs.getString("GioiTinh"));
                vec.add(rs.getNString("SDT"));
                vec.add(rs.getString("Chức vụ"));
                vec.add(rs.getString("DiaChi"));
                                  
                model.addRow(vec);
            }
            tabNhanvien.setModel(model);
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(QLNhanvien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbbChucvu = new javax.swing.JComboBox<>();
        txtID = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabNhanvien = new javax.swing.JTable();
        btnThoat = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiachi = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        rdbNam = new javax.swing.JRadioButton();
        rdbNu = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí nhân viên");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("DANH SÁCH NHÂN VIÊN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 13, -1, -1));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Delete/Delete_16x16.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 396, -1, -1));

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Edit/Edit_16x16.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 396, -1, -1));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add/Add_16x16.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 396, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Mã nhân viên");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 77, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Họ tên");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 117, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Số điện thoại");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 214, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Địa chỉ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 290, -1, -1));
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 114, 139, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Chức vụ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 251, -1, 25));

        cbbChucvu.setBackground(new java.awt.Color(153, 255, 153));
        cbbChucvu.setForeground(new java.awt.Color(102, 102, 0));
        cbbChucvu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên order", "Tài xế", "Quản lí", "Phục vụ", "Bảo vệ" }));
        cbbChucvu.setToolTipText("");
        cbbChucvu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbChucvuItemStateChanged(evt);
            }
        });
        cbbChucvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbChucvuActionPerformed(evt);
            }
        });
        getContentPane().add(cbbChucvu, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 252, 139, -1));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 74, 139, -1));
        getContentPane().add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 211, 139, -1));

        tabNhanvien.setBackground(new java.awt.Color(255, 255, 153));
        tabNhanvien.setForeground(new java.awt.Color(102, 102, 255));
        tabNhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDNV", "Username", "Giới tính", "SDT", "Chức vụ", "Địa chỉ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabNhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabNhanvienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabNhanvien);
        if (tabNhanvien.getColumnModel().getColumnCount() > 0) {
            tabNhanvien.getColumnModel().getColumn(0).setMaxWidth(50);
            tabNhanvien.getColumnModel().getColumn(3).setPreferredWidth(30);
            tabNhanvien.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 74, 710, 250));

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Undo/Undo_16x16.png"))); // NOI18N
        btnThoat.setText("Exit");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 390, -1, -1));

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Refresh/Refresh_16x16.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 390, -1, -1));

        txtDiachi.setColumns(20);
        txtDiachi.setRows(5);
        jScrollPane1.setViewportView(txtDiachi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 319, 244, 59));

        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("Giới tính");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 164, -1, -1));

        rdbNam.setForeground(new java.awt.Color(0, 51, 204));
        rdbNam.setText("Nam");
        getContentPane().add(rdbNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 160, -1, -1));

        rdbNu.setForeground(new java.awt.Color(0, 51, 204));
        rdbNu.setText("Nữ");
        getContentPane().add(rdbNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 160, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/imagesNVIEN.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 1030, 435));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        cbbChucvu.setSelectedItem(0);
        txtID.setText("");
        txtUsername.setText("");
        txtSDT.setText("");
        txtDiachi.setText("");
        txtID.setEnabled(true);    
        rdbNu.setSelected(true);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        DBAccess acc = new DBAccess();
        acc.connect();
        if(txtID.getText().equals("") || txtSDT.getText().equals("") || txtUsername.getText().equals("") || txtDiachi.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "vui lòng điền đầy đủ thông tin");
        }
        else
        {
            ButtonGroup group = new ButtonGroup();
            group.add(rdbNu);
            group.add(rdbNam);
            String IDNV = txtID.getText();
            String Username = txtUsername.getText();
            String GioiTinh = "";
            if(rdbNu.isSelected() == true)
            {
                GioiTinh = rdbNu.getText();
            }
            else
            {
                GioiTinh = rdbNam.getText();
            }           
            String SDT = txtSDT.getText();
            String IDCV =  (String) cbbChucvu.getSelectedItem();
            String Diachi = txtDiachi.getText();
            ResultSet rs = acc.Query("select IDNV from NhanVien where IDNV = '"+IDNV+"'");
            try {
                if(rs.next())
                {
                    JOptionPane.showMessageDialog(this, "Mã nhân viên đã tồn tại !!!");
                }
                else
                {
                    acc.InsertNV(IDNV, Username,GioiTinh, SDT, IDCV, Diachi);
                }
            } catch (SQLException ex) {
                Logger.getLogger(QLNhanvien.class.getName()).log(Level.SEVERE, null, ex);
            }
            LoadData();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void tabNhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabNhanvienMouseClicked
        // TODO add your handling code here:
        ButtonGroup group = new ButtonGroup();
        group.add(rdbNu);
        group.add(rdbNam);
        int i = tabNhanvien.getSelectedRow();
        TableModel model = tabNhanvien.getModel();
        cbbChucvu.setSelectedItem(model.getValueAt(i, 4).toString());
        txtID.setText(model.getValueAt(i, 0).toString());
        txtUsername.setText(model.getValueAt(i, 1).toString());
        txtSDT.setText(model.getValueAt(i, 3).toString());
        txtDiachi.setText(model.getValueAt(i, 5).toString());   
        if(model.getValueAt(i, 2).toString().equals("Nữ"))
        {
            rdbNu.setSelected(true);
            rdbNam.setSelected(false);
        }
        else
        {
            rdbNam.setSelected(true);
            rdbNu.setSelected(false);  
        }
        txtID.setEditable(false);
    }//GEN-LAST:event_tabNhanvienMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        DBAccess acc = new DBAccess();
        acc.connect();
        if(txtSDT.getText().equals("") || txtUsername.getText().equals("") || txtDiachi.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "vui lòng điền đầy đủ thông tin");
        }
        else
        {
            ButtonGroup group = new ButtonGroup();
            group.add(rdbNu);
            group.add(rdbNam);
            String GioiTinh = "";
            if(rdbNu.isSelected() == true)
            {
                GioiTinh = rdbNu.getText();
            }
            else
            {
                GioiTinh = rdbNam.getText();
            }
            String IDNV = txtID.getText();
            String username = txtUsername.getText();
            String SDT = txtSDT.getText();
            String IDCV =  (String) cbbChucvu.getSelectedItem();
            String Diachi  = txtDiachi.getText();
            try {
                acc.UpdateNV(IDNV, username,GioiTinh, SDT, IDCV, Diachi);
            } catch (SQLException ex) {
                Logger.getLogger(QLNhanvien.class.getName()).log(Level.SEVERE, null, ex);
            }
            LoadData();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        DBAccess acc = new DBAccess();
        acc.connect();
        int remove = tabNhanvien.getSelectedRow();
        if(remove == -1)
        {
            JOptionPane.showMessageDialog(null, "vui lòng chọn 1 dòng để xóa !!!");
        }
        else
        {
            try {
                String IDNV = txtID.getText();
                acc.deleteNV(IDNV);
                System.out.print(IDNV);
            } catch (SQLException ex) {
                Logger.getLogger(QLNhanvien.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        LoadData();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void cbbChucvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbChucvuActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbbChucvuActionPerformed

    private void cbbChucvuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbChucvuItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbChucvuItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLNhanvien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbChucvu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdbNam;
    private javax.swing.JRadioButton rdbNu;
    private javax.swing.JTable tabNhanvien;
    private javax.swing.JTextArea txtDiachi;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
