/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLi;

import DataBase.DBAccess;
import static LoginKH.DangNhap_1.sodienthoai;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.TableModel;

/**
 *
 * @author ASUS
 */
public class QLOderOL extends javax.swing.JFrame {
    public static ResultSet rs = null,rs1 = null, rs2 = null ;
    Connection con;
    public PreparedStatement pet;

    /**
     * Creates new form QLDatHang
     */
    public QLOderOL() {
        initComponents();
        LoadDataHDOL();
        LoadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void LoadDataHDOL () 
    {
        DBAccess acc = new DBAccess();
        try
        {
            rs = acc.Query("select IDHD,GiaoHang.sodienthoai,HoTen,GioDat,NgayDat,MucKM,TongTien,TenLoaiTT,DCgiaohang,TinhTrang\n" +
                           "from GiaoHang,LoaiTT,Taikhoan\n" +
                           "where GiaoHang.IDLTT = LoaiTT.IDLTT and GiaoHang.sodienthoai = Taikhoan.sodienthoai order by IDHD  ");
            String [] arr = {"Mã hóa đơn","Số điện thoại","Họ tên","Time","Ngày đặt","Loại thanh toán","Địa chỉ giao hàng","Mức KM","Tổng tiền","TinhTrang"};
            DefaultTableModel model = new DefaultTableModel(arr,0);
            while(rs.next())
            {
                Vector vec = new Vector();
                vec.add(rs.getInt("IDHD"));
                vec.add(rs.getString("sodienthoai"));
                vec.add(rs.getString("HoTen"));
                vec.add(rs.getString("GioDat"));
                vec.add(rs.getString("NgayDat"));
                vec.add(rs.getString("TenLoaiTT"));
                vec.add(rs.getString("DCgiaohang"));
                vec.add(rs.getInt("MucKM"));
                vec.add(rs.getString("TongTien"));
                vec.add(rs.getString("TinhTrang"));
                
                model.addRow(vec);
            }
            rs2 = acc.Query("select sum(TongTien) as TongThu from GiaoHang");
            while(rs2.next())
            {
                txtTongtien.setText(rs2.getString("TongThu")+ " VND");
            }
            tabGiaohang.setModel(model);
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        setColumn();
        txtTongtien.setEditable(false);
    }
    public void LoadData()
    {
        Date batdau = cldBatdau.getDate();
        System.out.println(batdau);
    }
    public void LoadDataSP (String IDHD) 
    {
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;Database=AppTraSua;user=DoanJava;password=12345";
            con = DriverManager.getConnection(url);
            String sql = "select QLGioHang.IDHD,TenSP,SoLuong,Topping,TongTienSP,Gia\n" +
                         "from QLGioHang,Sanpham,GiaoHang\n" +
                         "where QLGioHang.IDHD = GiaoHang.IDHD and QLGioHang.IDSP = Sanpham.IDSP and QLGioHang.IDHD = ? ";
            pet = con.prepareStatement(sql);
            pet.setString(1, IDHD);
            rs1 = pet.executeQuery();
            String [] arr = {"Mã hóa dơn","Tên sản phẩm","Đơn giá","Số lượng","Topping","Tổng tiền sản phẩm"};
            DefaultTableModel model = new DefaultTableModel(arr,0);
            while(rs1.next())
            {
                Vector vec = new Vector();
                vec.add(rs1.getString("IDHD"));
                vec.add(rs1.getString("TenSP"));
                vec.add(rs1.getString("Gia"));
                vec.add(rs1.getInt("SoLuong")); 
                vec.add(rs1.getString("Topping"));
                vec.add(rs1.getInt("TongTienSP"));
                
                model.addRow(vec);
            }
            tabSanpham.setModel(model);
            rs1.close();
            pet.close();
            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        setColumn();
    }
    public void XoaTrangTABBLE()
    {
        DefaultTableModel m = (DefaultTableModel)tabGiaohang.getModel();
        m.getDataVector().removeAllElements();
        m.fireTableDataChanged();
    }
    public void setColumn()
    {
        tabGiaohang.getColumnModel().getColumn(0).setPreferredWidth(20);
        tabGiaohang.getColumnModel().getColumn(1).setPreferredWidth(30);
        tabGiaohang.getColumnModel().getColumn(2).setPreferredWidth(90);
        tabGiaohang.getColumnModel().getColumn(3).setPreferredWidth(40);
        tabGiaohang.getColumnModel().getColumn(4).setPreferredWidth(40);
        tabGiaohang.getColumnModel().getColumn(5).setPreferredWidth(90);
        tabGiaohang.getColumnModel().getColumn(6).setPreferredWidth(300);
        tabGiaohang.getColumnModel().getColumn(7).setPreferredWidth(30);
        tabGiaohang.getColumnModel().getColumn(8).setPreferredWidth(40);
        tabGiaohang.getColumnModel().getColumn(9).setPreferredWidth(50);
        tabGiaohang.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        
        tabSanpham.getColumnModel().getColumn(0).setPreferredWidth(40);
        tabSanpham.getColumnModel().getColumn(1).setPreferredWidth(40);
        tabSanpham.getColumnModel().getColumn(2).setPreferredWidth(40);
        tabSanpham.getColumnModel().getColumn(3).setPreferredWidth(120);
        tabSanpham.getColumnModel().getColumn(4).setPreferredWidth(30);
        tabSanpham.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabGiaohang = new javax.swing.JTable();
        btnThoat = new javax.swing.JButton();
        txtTongtien = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnLoc = new javax.swing.JButton();
        cldBatdau = new com.toedter.calendar.JDateChooser();
        cldKetthuc = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabSanpham = new javax.swing.JTable();
        btnReload = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí order online");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("THỐNG KÊ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Tổng thu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 710, -1, -1));

        tabGiaohang.setBackground(new java.awt.Color(255, 255, 102));
        tabGiaohang.setForeground(new java.awt.Color(204, 0, 0));
        tabGiaohang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Số điện thoại", "Họ tên", "Time", "Ngày đăt", "Loại thanh toán", "Địa chỉ giao hàng", "Mức KM", "Tổng tiền", "Tình trạng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabGiaohang.getTableHeader().setReorderingAllowed(false);
        tabGiaohang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabGiaohangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabGiaohang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 1290, 210));

        btnThoat.setForeground(new java.awt.Color(0, 0, 255));
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Undo/Undo_16x16.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 708, -1, -1));
        getContentPane().add(txtTongtien, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 710, 107, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel2.setText("Bắt đầu ");

        jLabel4.setText("Kết thúc");

        btnLoc.setBackground(new java.awt.Color(255, 204, 204));
        btnLoc.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnLoc.setForeground(new java.awt.Color(153, 0, 153));
        btnLoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search/Search_16x16.png"))); // NOI18N
        btnLoc.setText("Lọc");
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocActionPerformed(evt);
            }
        });

        cldBatdau.setDateFormatString("yyyy-MM-dd");

        cldKetthuc.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cldKetthuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cldBatdau, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cldBatdau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(cldKetthuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnLoc)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, -1));

        tabSanpham.setBackground(new java.awt.Color(255, 255, 153));
        tabSanpham.setForeground(new java.awt.Color(255, 51, 51));
        tabSanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Tên sản phẩm", "Số lượng", "Topping", "Tổng tiền sản phẩm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabSanpham.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tabSanpham);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 1290, 200));

        btnReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Refresh/Refresh_16x16.png"))); // NOI18N
        btnReload.setText("Reload");
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });
        getContentPane().add(btnReload, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 710, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/qlodol.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocActionPerformed
        // TODO add your handling code here:
        DBAccess acc = new DBAccess();
        if(cldBatdau.getDateFormatString().equals("") || cldBatdau.getDateFormatString().equals("") )
        {
            XoaTrangTABBLE();
        }
        else
        {
            try {
                SimpleDateFormat formaterBD = new SimpleDateFormat("yyyy-MM-dd");
                String batdau = formaterBD.format(cldBatdau.getDate().getTime());
                SimpleDateFormat formaterKT = new SimpleDateFormat("yyyy-MM-dd");
                String ketthuc = formaterKT.format(cldKetthuc.getDate().getTime());
                rs = acc.Query("select IDHD,GiaoHang.sodienthoai,HoTen,GioDat,NgayDat,MucKM,TongTien,TenLoaiTT,DCgiaohang,TinhTrang\n" +
                                "from GiaoHang,LoaiTT,Taikhoan\n" +
                                "where GiaoHang.IDLTT = LoaiTT.IDLTT and GiaoHang.sodienthoai = Taikhoan.sodienthoai and NgayDat between '"+batdau+"' and '"+ketthuc+"' \n" +
                                "order by IDHD ");
                String [] arr = {"Mã hóa đơn","Số điện thoại","Họ tên","Time","Ngày đặt","Loại thanh toán","Địa chỉ giao hàng","Mức KM","Tổng tiền","TinhTrang"};
                DefaultTableModel model = new DefaultTableModel(arr,0);
                while(rs.next())
                {
                    Vector vec = new Vector();
                    vec.add(rs.getInt("IDHD"));
                    vec.add(rs.getString("sodienthoai"));
                    vec.add(rs.getString("HoTen"));
                    vec.add(rs.getString("GioDat"));
                    vec.add(rs.getString("NgayDat"));
                    vec.add(rs.getString("TenLoaiTT"));
                    vec.add(rs.getString("DCgiaohang"));
                    vec.add(rs.getInt("MucKM"));
                    vec.add(rs.getString("TongTien"));
                    vec.add(rs.getString("TinhTrang"));

                    model.addRow(vec);
                }
                tabGiaohang.setModel(model);
                rs2 = acc.Query("select sum(TongTien) as TongThu from GiaoHang where NgayDat between '"+batdau+"' and '"+ketthuc+"'");
                while(rs2.next())
                {
                    txtTongtien.setText(rs2.getString("TongThu")+ " VND");
                }
                rs.close();
                rs2.close();
            } catch (SQLException ex) {
                Logger.getLogger(QLOderOL.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        setColumn();
        String IDHD = null;
        LoadDataSP(IDHD);
    }//GEN-LAST:event_btnLocActionPerformed

    private void tabGiaohangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabGiaohangMouseClicked
        // TODO add your handling code here:
        int i = tabGiaohang.getSelectedRow();
        TableModel model = tabGiaohang.getModel();
        String IDHD = model.getValueAt(i, 0).toString();
        LoadDataSP(IDHD);
    }//GEN-LAST:event_tabGiaohangMouseClicked

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        // TODO add your handling code here:
        LoadData();
    }//GEN-LAST:event_btnReloadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLOderOL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLOderOL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLOderOL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLOderOL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLOderOL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoc;
    private javax.swing.JButton btnReload;
    private javax.swing.JButton btnThoat;
    private com.toedter.calendar.JDateChooser cldBatdau;
    private com.toedter.calendar.JDateChooser cldKetthuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabGiaohang;
    private javax.swing.JTable tabSanpham;
    private javax.swing.JTextField txtTongtien;
    // End of variables declaration//GEN-END:variables
}
