/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLi;

import DataBase.DBAccess;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.rmi.CORBA.Util;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ASUS
 */
public class QLSanPham extends javax.swing.JFrame {
    Connection con;
    public PreparedStatement pet;
    public static ResultSet rs = null ;
    public Statement stmt;

    /**
     * Creates new form QLSanPham
     */
    DefaultTableModel model;
    public QLSanPham() {
        initComponents();
        LoadData();    
    }
    public void LoadData () 
    {
        DBAccess acc = new DBAccess();
        acc.connect();
        try { 
            rs = acc.GetData2();
            tabSanpham.removeAll();
            String [] arr = {"IDSP","Tên SP","Loại","Giá(VND)","Chi Tiết"};
            model = new DefaultTableModel(arr,0);
            while(rs.next())
            {   
                Vector vec = new Vector();
                vec.add(rs.getString("IDSP"));
                vec.add(rs.getString("TenSP"));
                vec.add(rs.getNString("TenLoai")); 
                vec.add(rs.getString("Gia"));
                vec.add(rs.getString("ChiTiet"));
                
                model.addRow(vec);
            }
            tabSanpham.setModel(model);
            rs.close();
        }
        catch(Exception ex)
        {
            Logger.getLogger(QLSanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtIDSP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtGia = new javax.swing.JFormattedTextField();
        cbbLoai = new javax.swing.JComboBox<>();
        txtTensp = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtChitiet = new javax.swing.JTextPane();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabSanpham = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí sản phẩm");
        setBackground(new java.awt.Color(153, 255, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("DANH SÁCH SẢN PHẨM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));
        getContentPane().add(txtIDSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 150, 25));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mã sản phẩm");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tên sản phẩm");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Loại");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 25));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Đơn giá");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Chi Tiết");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 25));
        getContentPane().add(txtGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 120, -1));

        cbbLoai.setBackground(new java.awt.Color(153, 255, 153));
        cbbLoai.setForeground(new java.awt.Color(102, 102, 0));
        cbbLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trà sữa", "Trà sữa xanh", "Trà hoa quả" }));
        cbbLoai.setToolTipText("");
        cbbLoai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbLoaiItemStateChanged(evt);
            }
        });
        cbbLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbLoaiActionPerformed(evt);
            }
        });
        getContentPane().add(cbbLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 130, -1));
        getContentPane().add(txtTensp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 200, -1));

        jScrollPane3.setViewportView(txtChitiet);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 290, 60));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add/Add_16x16.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Edit/Edit_16x16.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Delete/Delete_16x16.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        btnRefresh.setBackground(new java.awt.Color(255, 255, 204));
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Refresh/Refresh_16x16.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, -1, -1));

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Undo/Undo_16x16.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 360, -1, -1));

        tabSanpham.setBackground(new java.awt.Color(255, 255, 204));
        tabSanpham.setForeground(new java.awt.Color(255, 51, 51));
        tabSanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDSP", "Tên SP", "Loại", "Giá", "Chi Tiết"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabSanpham.getTableHeader().setReorderingAllowed(false);
        tabSanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabSanphamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabSanpham);
        if (tabSanpham.getColumnModel().getColumnCount() > 0) {
            tabSanpham.getColumnModel().getColumn(0).setMinWidth(10);
            tabSanpham.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 760, 260));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/imageQLSP.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        DBAccess acc = new DBAccess();
        acc.connect();
        if(txtIDSP.getText().equals("") || txtTensp.getText().equals("") || txtChitiet.getText().equals("") || txtGia.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "vui lòng điền đầy đủ thông tin");
        }
        else
        {
            String IDSP = txtIDSP.getText();
            String TenSP = txtTensp.getText();
            String IDLoai =  (String) cbbLoai.getSelectedItem();
            String ChiTiet = txtChitiet.getText();
            int Gia = Integer.parseInt(txtGia.getText());
            ResultSet rs = acc.Query("select IDSP from Sanpham where IDSP = '"+IDSP+"'");
            try {
                if(rs.next())
                {
                    JOptionPane.showMessageDialog(this, "Mã sản phẩm đã tồn tại !!!");
                }
                else
                {
                    acc.InsertSP(IDSP,TenSP,IDLoai,ChiTiet,Gia);
                }
            } catch (SQLException ex) {
                Logger.getLogger(QLSanPham.class.getName()).log(Level.SEVERE, null, ex);
            }
            LoadData();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        DBAccess acc = new DBAccess();
        acc.connect();
        if(txtIDSP.getText().equals("") || txtTensp.getText().equals("") || txtChitiet.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "vui lòng điền đầy đủ thông tin");
        }
        else
        {
            String IDSP = txtIDSP.getText();
            String TenSP = txtTensp.getText();
            String IDLoai =  (String) cbbLoai.getSelectedItem();
            String ChiTiet = txtChitiet.getText();
            String Gia = txtGia.getText();
            System.out.println(Gia);      
            try {
                acc.UpdateSP(IDSP,TenSP,IDLoai,ChiTiet,Gia);
            } catch (SQLException ex) {
                Logger.getLogger(QLSanPham.class.getName()).log(Level.SEVERE, null, ex);
            }
            LoadData();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        DBAccess acc = new DBAccess();
        acc.connect();
        int remove = tabSanpham.getSelectedRow();
        if(remove == -1)
        {
            JOptionPane.showMessageDialog(null, "vui lòng chọn 1 dòng để xóa !!!");
        }
        else
        {
            try {
                String IDSP = txtIDSP.getText();
                acc.deleteSP(IDSP);
            } catch (SQLException ex) {
                Logger.getLogger(QLSanPham.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        LoadData();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        cbbLoai.setSelectedIndex(1);
        txtIDSP.setText("");
        txtTensp.setText("");
        txtChitiet.setText("");
        txtGia.setText("");
        txtIDSP.setEnabled(true);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tabSanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabSanphamMouseClicked
        // TODO add your handling code here:
        int i = tabSanpham.getSelectedRow();
        TableModel model = tabSanpham.getModel();
        cbbLoai.setSelectedItem(model.getValueAt(i, 2).toString());
        txtIDSP.setText(model.getValueAt(i, 0).toString());
        txtTensp.setText(model.getValueAt(i, 1).toString());
        txtGia.setText(model.getValueAt(i, 3).toString());
        txtChitiet.setText(model.getValueAt(i, 4).toString());
        txtIDSP.setEditable(false);
    }//GEN-LAST:event_tabSanphamMouseClicked

    private void cbbLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbLoaiActionPerformed

    private void cbbLoaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbLoaiItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbLoaiItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLSanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbLoai;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabSanpham;
    private javax.swing.JTextPane txtChitiet;
    private javax.swing.JFormattedTextField txtGia;
    private javax.swing.JTextField txtIDSP;
    private javax.swing.JTextField txtTensp;
    // End of variables declaration//GEN-END:variables
}
