/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLi;

import DataBase.DBAccess;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ASUS
 */
public class QLTaiKhoan extends javax.swing.JFrame {
    Connection con;
    public PreparedStatement pet,pet1;
    public static ResultSet rs = null ,rs1 = null;
    

    /**
     * Creates new form TaiKhoan
     */
    public QLTaiKhoan() {
        initComponents();
        LoadData();
    }
    public void XoaTrangTABBLE()
    {
        DefaultTableModel m = (DefaultTableModel)tabTaikhoan.getModel();
        m.getDataVector().removeAllElements();
        m.fireTableDataChanged();
    }
    public void LoadData () 
    {
        DBAccess acc = new DBAccess();
        acc.connect();
        try { 
            rs = acc.GetDataTK2();
            tabTaikhoan.removeAll();
            String [] arr = {"Số điện thoại","Họ Tên","Giới tính","Email","Địa chỉ","password"};
            DefaultTableModel model = new DefaultTableModel(arr,0);
            while(rs.next())
            {
                Vector vec = new Vector();
                vec.add(rs.getString("sodienthoai"));
                vec.add(rs.getString("HoTen"));
                vec.add(rs.getString("GioiTinh"));
                vec.add(rs.getString("Email"));  
                vec.add(rs.getString("DiaChi"));
                vec.add(rs.getString("password"));
                model.addRow(vec);
            }
            tabTaikhoan.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(QLTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtHoTen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabTaikhoan = new javax.swing.JTable();
        btnThoat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí tài khoản");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DANH SÁCH TÀI KHOẢN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtHoTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHoTenKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHoTenKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHoTenKeyTyped(evt);
            }
        });

        jLabel2.setText("HỌ TÊN");

        jLabel4.setText("SDT");

        txtSDT.setText("\n");
        txtSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSDTKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSDTKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(txtSDT))
                .addGap(99, 99, 99))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 330, 130));

        tabTaikhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số điện thoại", "Họ Tên", "Giới tính", "Email", "Địa chỉ", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabTaikhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabTaikhoanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabTaikhoan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 730, 189));

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Undo/Undo_16x16.png"))); // NOI18N
        btnThoat.setText("EXIT");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, -1, -1));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Delete/Delete_16x16.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, -1, -1));

        btnRefresh.setBackground(new java.awt.Color(255, 255, 204));
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Refresh/Refresh_16x16.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/imageQLTK.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 536));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabTaikhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabTaikhoanMouseClicked
        // TODO add your handling code here:
        int i = tabTaikhoan.getSelectedRow();
        TableModel model = tabTaikhoan.getModel();
        txtSDT.setText(model.getValueAt(i, 0).toString());
        txtHoTen.setText(model.getValueAt(i, 1).toString());
        txtSDT.setEditable(false);
        txtHoTen.setEditable(false);
    }//GEN-LAST:event_tabTaikhoanMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        DBAccess acc = new DBAccess();
        acc.connect();
        int remove = tabTaikhoan.getSelectedRow();
        if(remove == -1)
        {
            JOptionPane.showConfirmDialog(null, "vui lòng chọn 1 dòng để xóa !!!");
        }
        else
        { 
            try {
                String sodienthoai = txtSDT.getText();
                acc.deleteTK(sodienthoai);
                System.out.println(sodienthoai);
            } catch (SQLException ex) {
                Logger.getLogger(QLTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
        LoadData();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        txtHoTen.setText("");
        txtSDT.setText("");
        txtHoTen.setEditable(true);
        txtSDT.setEditable(true);
        LoadData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void txtHoTenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoTenKeyTyped
       
    }//GEN-LAST:event_txtHoTenKeyTyped

    private void txtHoTenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoTenKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenKeyPressed

    private void txtSDTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSDTKeyTyped
            // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTKeyTyped

    private void txtSDTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSDTKeyReleased
        txtHoTen.setText("");
        XoaTrangTABBLE();
        String sdt=txtSDT.getText();
        DBAccess acc = new DBAccess();
        acc.connect();   
         try{
            if(txtSDT.getText()=="")
            {
                LoadData();
            }
            else
            {
              
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;Database=AppTraSua;user=DoanJava;password=12345";
            con = DriverManager.getConnection(url);
            String [] arr = {"Số điện thoại","Họ Tên","Giới tính","Email","Địa chỉ","password"};
            DefaultTableModel model = new DefaultTableModel(arr,0);
            String sql = "select sodienthoai,HoTen,GioiTinh,Email,DiaChi,password from Taikhoan,GioiTinh where sodienthoai like  N'%"+sdt+"%' and GioiTinh.IDGT = Taikhoan.IDGT ";
                    pet = con.prepareStatement(sql);
                    rs = pet.executeQuery();
                    while(rs.next())
                    {
                        Vector vec = new Vector();
                        vec.add(rs.getString("sodienthoai"));
                        vec.add(rs.getString("HoTen"));
                        vec.add(rs.getString("GioiTinh"));
                        vec.add(rs.getString("Email"));  
                        vec.add(rs.getString("DiaChi"));
                        vec.add(rs.getString("password"));
                        model.addRow(vec);
                    }
                    tabTaikhoan.setModel(model);
            }
         }
          catch(Exception e){
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, e);
        }  
    }//GEN-LAST:event_txtSDTKeyReleased

    private void txtHoTenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoTenKeyReleased
        txtSDT.setText("");
        XoaTrangTABBLE();
        String hoten=txtHoTen.getText();
        DBAccess acc = new DBAccess();
        acc.connect();   
         try{
            if(txtHoTen.getText()=="")
            {
                LoadData();
            }
            else
            {
                rs = acc.Query("select sodienthoai,HoTen,GioiTinh,Email,DiaChi,password from Taikhoan,GioiTinh where HoTen like  '%"+hoten+"%' and GioiTinh.IDGT = Taikhoan.IDGT ");
                String [] arr = {"Số điện thoại","Họ Tên","Giới tính","Email","Địa chỉ","password"};
                DefaultTableModel model = new DefaultTableModel(arr,0);
                while(rs.next())
                {
                    Vector vec = new Vector();
                    vec.add(rs.getString("sodienthoai"));
                    vec.add(rs.getString("HoTen"));
                    vec.add(rs.getString("GioiTinh"));
                    vec.add(rs.getString("Email"));  
                    vec.add(rs.getString("DiaChi"));
                    vec.add(rs.getString("password"));
                    model.addRow(vec);
                }
                tabTaikhoan.setModel(model);
            }
         }
          catch(Exception e){
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, e);
        }     // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLTaiKhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabTaikhoan;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtSDT;
    // End of variables declaration//GEN-END:variables
}
