/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLi;

import Admin.*;
import QuanLi.QLNhanvien;
import QuanLi.*;


/**
 *
 * @author ASUS
 */
public class QuanLi extends javax.swing.JFrame {

    /**
     * Creates new form QuanLi
     */
    public QuanLi() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnQLNV = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnQLSP = new javax.swing.JButton();
        btnQLTK = new javax.swing.JButton();
        btnQLTKNV = new javax.swing.JButton();
        btnQLKM = new javax.swing.JButton();
        btnQLThongKe = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Papyrus", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("QUẢN LÍ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        btnQLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Open/Open_16x16.png"))); // NOI18N
        btnQLNV.setText("Quản lí thông tin nhân viên");
        btnQLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNVActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 84, 217, -1));

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Undo/Undo_16x16.png"))); // NOI18N
        btnThoat.setText("Exit");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        btnQLSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Open/Open_16x16.png"))); // NOI18N
        btnQLSP.setText("Quản lí thông tin sản phẩm");
        btnQLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLSPActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 202, 217, -1));

        btnQLTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Open/Open_16x16.png"))); // NOI18N
        btnQLTK.setText("Quản lí tài khoản khách hàng");
        btnQLTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTKActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 140, -1, -1));

        btnQLTKNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Open/Open_16x16.png"))); // NOI18N
        btnQLTKNV.setText("Quản lí tài khoản nhân viên");
        btnQLTKNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTKNVActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLTKNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 84, -1, -1));

        btnQLKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Open/Open_16x16.png"))); // NOI18N
        btnQLKM.setText("Quản lí sự kiện khuyến mãi");
        btnQLKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLKMActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLKM, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 140, -1, -1));

        btnQLThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Open/Open_16x16.png"))); // NOI18N
        btnQLThongKe.setText("Quản lí thống kê");
        btnQLThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLThongKeActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 202, 200, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/imageQLAD.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNVActionPerformed
        // TODO add your handling code here:
        QLNhanvien frm = new QLNhanvien();
        frm.setVisible(true);
    }//GEN-LAST:event_btnQLNVActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        Login frm = new Login();
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnQLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSPActionPerformed
        // TODO add your handling code here:
        QLSanPham frm = new QLSanPham();
        frm.setVisible(true);
    }//GEN-LAST:event_btnQLSPActionPerformed

    private void btnQLTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTKActionPerformed
        // TODO add your handling code here:
        QLTaiKhoan frm = new QLTaiKhoan();
        frm.setVisible(true);
    }//GEN-LAST:event_btnQLTKActionPerformed

    private void btnQLThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLThongKeActionPerformed
        // TODO add your handling code here:
        ThongKe frm = new ThongKe();
        frm.setVisible(true);
    }//GEN-LAST:event_btnQLThongKeActionPerformed

    private void btnQLKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLKMActionPerformed
        // TODO add your handling code here:
        QLSukienKM frm = new QLSukienKM();
        frm.setVisible(true);
    }//GEN-LAST:event_btnQLKMActionPerformed

    private void btnQLTKNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTKNVActionPerformed
        // TODO add your handling code here:
        QL_TK_Admin frm = new QL_TK_Admin();
        frm.setVisible(true);
    }//GEN-LAST:event_btnQLTKNVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQLKM;
    private javax.swing.JButton btnQLNV;
    private javax.swing.JButton btnQLSP;
    private javax.swing.JButton btnQLTK;
    private javax.swing.JButton btnQLTKNV;
    private javax.swing.JButton btnQLThongKe;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
