/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import DataBase.DBAccess;
import QuanLi.QLTaiKhoan;
import static QuanLi.QLTaiKhoan.rs;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Administrator
 */
public class QL_TK_Admin extends javax.swing.JFrame {
    public String tenTK = null;

    /**
     * Creates new form DangKiAdmin
     */
    public QL_TK_Admin() {
        initComponents();
        LoadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void LoadData () 
    {
        DBAccess acc = new DBAccess();
        acc.connect();
        try { 
            rs = acc.Query("select TaikhoanAD.IDNV,TaikhoanAD.username,password,[Chức vụ] from TaikhoanAD,NhanVien,Chucvu where TaikhoanAD.IDNV = NhanVien.IDNV and Chucvu.IDCV = NhanVien.IDCV");
            String [] arr = {"Mã nhân viên","Chức vụ","Tên tài khoản","Password"};
            DefaultTableModel model = new DefaultTableModel(arr,0);
            while(rs.next())
            {
                Vector vec = new Vector();
                vec.add(rs.getString("IDNV"));
                vec.add(rs.getNString("Chức vụ"));
                vec.add(rs.getString("username"));
                vec.add(rs.getString("password"));
                model.addRow(vec);
            }
            tabTaikhoanAD.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(QL_TK_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtChucvu.setEditable(false);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabTaikhoanAD = new javax.swing.JTable();
        btnXoa = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIDNV = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtChucvu = new javax.swing.JTextField();
        ckcShowpass = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tài khoản Admin");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabTaikhoanAD.setForeground(new java.awt.Color(102, 0, 102));
        tabTaikhoanAD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Chức vụ", "Tên tài khoản", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabTaikhoanAD.getTableHeader().setReorderingAllowed(false);
        tabTaikhoanAD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabTaikhoanADMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabTaikhoanAD);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 37, 515, 160));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Delete/Delete_16x16.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        btnRefresh.setBackground(new java.awt.Color(255, 255, 204));
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Refresh/Refresh_16x16.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, -1, -1));

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Undo/Undo_16x16.png"))); // NOI18N
        btnThoat.setText("Exit");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, -1, -1));
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 77, 139, 27));

        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 126, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Tên tài khoản");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 80, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Mã nhân viên");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 40, -1, -1));
        getContentPane().add(txtIDNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 37, 139, 26));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add/Add_16x16.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Edit/Edit_16x16.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Chức vụ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 25));

        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPassKeyTyped(evt);
            }
        });
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 140, 25));
        getContentPane().add(txtChucvu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 140, 27));

        ckcShowpass.setText("Hiện Mật khẩu");
        ckcShowpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckcShowpassActionPerformed(evt);
            }
        });
        getContentPane().add(ckcShowpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/imageQLTKAD.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabTaikhoanADMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabTaikhoanADMouseClicked
        // TODO add your handling code here:
        int i = tabTaikhoanAD.getSelectedRow();
        TableModel model = tabTaikhoanAD.getModel();
        txtChucvu.setText(model.getValueAt(i, 1).toString());
        txtIDNV.setText(model.getValueAt(i, 0).toString());
        txtUsername.setText(model.getValueAt(i, 2).toString());
        txtPass.setText(model.getValueAt(i, 3).toString());
        tenTK = model.getValueAt(i, 2).toString();
    }//GEN-LAST:event_tabTaikhoanADMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        DBAccess acc = new DBAccess();
        acc.connect();
        int remove = tabTaikhoanAD.getSelectedRow();
        if(remove == -1)
        {
            JOptionPane.showConfirmDialog(null, "vui lòng chọn 1 dòng để xóa !!!");
        }
        else
        {
            String Username = txtUsername.getText();
            acc.Update("delete from TaikhoanAD where username = '"+Username+"'");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        txtIDNV.setText("");
        txtUsername.setText("");
        txtPass.setText("");
        txtChucvu.setText("");
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        DBAccess acc = new DBAccess();
        acc.connect();
        if(txtIDNV.getText().equals("") || txtPass.getPassword().equals("") || txtUsername.getText().equals("") )
        {
            JOptionPane.showMessageDialog(this, "vui lòng điền đầy đủ thông tin");
        }
        else
        {
            String IDNV = txtIDNV.getText();
            String Username = txtUsername.getText(); 
            String password = new String(txtPass.getPassword());
            rs = acc.Query("select IDNV from NhanVien where IDNV = '"+IDNV+"'");
            try {
                if(rs.next())
                {
                    int kq = acc.Update("insert into TaikhoanAD values(N'"+Username+"','"+password+"','"+IDNV+"' ");
                    if(kq!=0){
                        JOptionPane.showMessageDialog(null,"Thêm thành công !!");    
                    }else{
                        JOptionPane.showMessageDialog(null,"Đã tồn tại tên tài khoản !!");
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Nhân viên không tồn tại !!!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(QL_TK_Admin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        LoadData();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        DBAccess acc = new DBAccess();
        acc.connect();
        if(txtIDNV.getText().equals("") || txtPass.getPassword().equals("") || txtUsername.getText().equals("") )
        {
            JOptionPane.showMessageDialog(this, "vui lòng điền đầy đủ thông tin");
        }
        else
        {
            String IDNV = txtIDNV.getText();
            String Username = txtUsername.getText(); 
            String password = new String(txtPass.getPassword());
            acc.Update("update TaikhoanAD set IDNV = '"+IDNV+"',username = '"+Username+"',password = '"+password+"' where username = '"+tenTK+"' ");   
        }
        LoadData();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyTyped
        if ((txtPass.getText() + evt.getKeyChar()).length() > 20) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPassKeyTyped

    private void ckcShowpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckcShowpassActionPerformed
        // TODO add your handling code here:
        if (ckcShowpass.isSelected()) {
            txtPass.setEchoChar((char)0);
        } else {
            txtPass.setEchoChar('*');
        }
    }//GEN-LAST:event_ckcShowpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_TK_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_TK_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_TK_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_TK_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QL_TK_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JCheckBox ckcShowpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabTaikhoanAD;
    private javax.swing.JTextField txtChucvu;
    private javax.swing.JTextField txtIDNV;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
